### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by sruthy-j-mallya** [sruthy-j-mallya/neeto-ui-challenge#15]

**Comment by sruthy-j-mallya** [comment]
Deployed at [https://neetoui-sruthy-production.herokuapp.com](https://neetoui-sruthy-production.herokuapp.com)
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink  Please review

**Comment by yedhink** [comment]
@sruthy-j-mallya 

- [x] You've used the keyword `note` in the `contact` pane. Either ways no need to add any of such keywords in the placeholder since the title of the Pane already suggests what entity we are dealing with.
<img width="465" alt="image" src="https://user-images.githubusercontent.com/31244999/192735357-ded20f0d-0736-4b64-b5f2-6fa2bf7f41e7.png">

Once you make this change, go ahead and mark this task as completed and continue with the next task.
